version: '3.4'

services:
  misproject.database.mariadb:
    container_name: misproject.database.mariadb
    image: mariadb:latest
    restart: always

  misproject.database.phpmyadmin:
    container_name: misproject.database.phpmyadmin
    image: phpmyadmin:latest
    restart: always
    depends_on: 
      - misproject.database.mariadb

  misproject.api:
    depends_on: 
      - misproject.database.mariadb
      - misproject.database.phpmyadmin
    image: ${DOCKER_REGISTRY-}misprojectapi
    restart: always
    build:
      context: .
      dockerfile: MisProject_API/Dockerfile
