// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MisProject.DataLayer.Contexts;

#nullable disable

namespace MisProject.DataLayer.Migrations
{
    [DbContext(typeof(MisDbContext))]
    [Migration("20220303074452_Remove_UserName_AndMake_NationalCodeAsRequired")]
    partial class Remove_UserName_AndMake_NationalCodeAsRequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MisProject.DTOs.Entities.Permissions.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ParentPermissionId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("PermissionId");

                    b.HasIndex("ParentPermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            PermissionTitle = "پنل مدیریت"
                        },
                        new
                        {
                            PermissionId = 2,
                            PermissionTitle = "مدیریت کاربران"
                        },
                        new
                        {
                            PermissionId = 3,
                            ParentPermissionId = 2,
                            PermissionTitle = "افزودن کاربر"
                        },
                        new
                        {
                            PermissionId = 4,
                            ParentPermissionId = 2,
                            PermissionTitle = "ویرایش کاربر"
                        },
                        new
                        {
                            PermissionId = 5,
                            ParentPermissionId = 2,
                            PermissionTitle = "حذف کاربر"
                        },
                        new
                        {
                            PermissionId = 6,
                            ParentPermissionId = 2,
                            PermissionTitle = "تغییر رمز عبور کاربر"
                        },
                        new
                        {
                            PermissionId = 11,
                            ParentPermissionId = 2,
                            PermissionTitle = "تغییر دسترسی های کاربر"
                        },
                        new
                        {
                            PermissionId = 7,
                            PermissionTitle = "مدیریت نقش ها"
                        },
                        new
                        {
                            PermissionId = 8,
                            ParentPermissionId = 7,
                            PermissionTitle = "افزودن نقش جدید"
                        },
                        new
                        {
                            PermissionId = 9,
                            ParentPermissionId = 7,
                            PermissionTitle = "ویرایش نقش"
                        },
                        new
                        {
                            PermissionId = 10,
                            ParentPermissionId = 7,
                            PermissionTitle = "حذف نقش"
                        });
                });

            modelBuilder.Entity("MisProject.DTOs.Entities.Permissions.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RolePermissionId = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 11,
                            PermissionId = 11,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("MisProject.DTOs.Entities.Users.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            IsDeleted = false,
                            RoleName = "مدیر وبسایت"
                        },
                        new
                        {
                            RoleId = 2,
                            IsDeleted = false,
                            RoleName = "کاربر"
                        });
                });

            modelBuilder.Entity("MisProject.DTOs.Entities.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActiveCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FatherName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FixedEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HomeNumber")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("IdentityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Interests")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("RegisterTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TelegramId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ActiveCode = "4774d6cf92a744f9b181609003b31e7d",
                            Email = "Admin@Admin.com",
                            FirstName = "Admin",
                            FixedEmail = "ADMIN@ADMIN.COM",
                            IdentityCode = "045f5b119de54909ab6630eae9a0b532",
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            IsPhoneNumberConfirmed = true,
                            LastName = "Admin",
                            NationalCode = "1080000001",
                            Password = "045e9902f2aca62f48117c43dfbd18cb",
                            RegisterTime = new DateTime(2022, 2, 1, 17, 1, 10, 967, DateTimeKind.Local).AddTicks(1720)
                        },
                        new
                        {
                            UserId = 2,
                            ActiveCode = "384528b9580f4acfbcc90f2f25ce08b7",
                            Email = "User2@Users.com",
                            FirstName = "User",
                            FixedEmail = "USER2@USERS.COM",
                            IdentityCode = "0dcb7d233a064c5580269c07a15bfaf3",
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            IsPhoneNumberConfirmed = true,
                            LastName = "Usr2",
                            NationalCode = "1080000002",
                            Password = "471e5243d0db300de1019fed26d3ffb1",
                            RegisterTime = new DateTime(2022, 2, 1, 17, 1, 10, 974, DateTimeKind.Local).AddTicks(8386)
                        },
                        new
                        {
                            UserId = 3,
                            ActiveCode = "1191b1fe89924cc2b6e47af84b1eb0a0",
                            Email = "User3@Users.com",
                            FirstName = "User",
                            FixedEmail = "USER3@USERS.COM",
                            IdentityCode = "7cf1a61f722941b289e2c6a31983dcd3",
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            IsPhoneNumberConfirmed = true,
                            LastName = "Usr3",
                            NationalCode = "1080000003",
                            Password = "471e5243d0db300de1019fed26d3ffb1",
                            RegisterTime = new DateTime(2022, 2, 1, 17, 1, 10, 974, DateTimeKind.Local).AddTicks(8753)
                        });
                });

            modelBuilder.Entity("MisProject.DTOs.Entities.Users.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            UserRoleId = 2,
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            UserRoleId = 3,
                            RoleId = 2,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MisProject.DTOs.Entities.Permissions.Permission", b =>
                {
                    b.HasOne("MisProject.DTOs.Entities.Permissions.Permission", "ParentPermission")
                        .WithMany()
                        .HasForeignKey("ParentPermissionId");

                    b.Navigation("ParentPermission");
                });

            modelBuilder.Entity("MisProject.DTOs.Entities.Permissions.RolePermission", b =>
                {
                    b.HasOne("MisProject.DTOs.Entities.Permissions.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MisProject.DTOs.Entities.Users.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MisProject.DTOs.Entities.Users.UserRole", b =>
                {
                    b.HasOne("MisProject.DTOs.Entities.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MisProject.DTOs.Entities.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MisProject.DTOs.Entities.Permissions.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MisProject.DTOs.Entities.Users.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MisProject.DTOs.Entities.Users.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
